### ISSUE TITLE
result code 4??

### ISSUE THREAD

**Issue by AubreyTheSilly** [murikistudio/game-jolt-api#6]
![image](https://github.com/user-attachments/assets/d4a8c8df-dd17-45fa-8e45-77d5a06d30c4)
what is happening? probably just my bad code but I'd like to know

**Comment by joelgomes1994** [comment]
Hello! It seems that error 4 is due to a connection error (see the [HTTPRequest result codes](https://docs.godotengine.org/en/stable/classes/class_httprequest.html#enum-httprequest-result) on the official documentation). Check if a firewall is blocking your Godot executable or if your network is working.

```
RESULT_CONNECTION_ERROR = 4
Request failed due to connection (read/write) error.
```

![image](https://github.com/user-attachments/assets/aab84cef-f448-46ef-995d-7649022510ec)

![image](https://github.com/user-attachments/assets/2e386b92-a51a-4933-9b53-f31a132de615)

**Comment by AubreyTheSilly** [comment]
Oop okay! now I know (I used a VPN to work on my game at school but it must've worked for requests)
