### ISSUE TITLE
Users Auth not grabbing game id

### ISSUE THREAD

**Issue by ZultaCulu** [murikistudio/game-jolt-api#7]
I dont know what changed, but the users_aith function isn't grabbing the game id. I've set it, and when I print it in the console it shows up, but users_auth doesnt see it. This is a new issue for me. It was working before. I've already tried removing the plugin, and readding, but nothing changed.

![Screenshot 2024-08-16 180312](https://github.com/user-attachments/assets/d67e4107-3b9e-4b7f-bf45-f215798da817)
![Screenshot 2024-08-16 180248](https://github.com/user-attachments/assets/b6292baf-86e6-4209-9ee9-401d147ccf12)
![Screenshot 2024-08-16 180228](https://github.com/user-attachments/assets/e0a3e30b-1de6-4b9a-bd70-85398901c041)

**Comment by joelgomes1994** [comment]
Hello, and thanks for the report! That's strange, I didn't change this in the previous versions of the plugin, and I'm also using Godot 4.3, I couldn't reproduce the issue.

Try changing the `set_game_id `method in `gamejolt.gd`:

```
# Set the game ID needed for all tasks.
func set_game_id(value: String) -> void:
	var changed := game_id != value
	game_id = value

	if changed:
		emit_signal("game_id_changed")
```

Maybe it's because the setter was skipping the change in some cases.

Also, check the _ready function of the same script and see if the setting paths match with the paths in Project Settings:

```
func _ready() -> void:
	_debug = ProjectSettings.get_setting("game_jolt/config/debug/enabled")
	game_id = ProjectSettings.get_setting("game_jolt/config/global/game_id")
	private_key = ProjectSettings.get_setting("game_jolt/config/global/private_key")
```

![image](https://github.com/user-attachments/assets/ef6210cc-7505-4c0e-a488-956cb84895d1)

**Comment by ZultaCulu** [comment]
I did that, but now I'm not getting the return for the users_auth in the console, just my print statment
![image](https://github.com/user-attachments/assets/856c2cf8-7dff-41ed-9433-d128cae27906)

**Comment by joelgomes1994** [comment]
> I did that, but now I'm not getting the return for the users_auth in the console, just my print statment

Could you share the code snippet where you call `users_auth` and print the result? If possible, also the output with the `Debug` option enabled in the settings.

**Comment by ZultaCulu** [comment]
oh. it works. I forgot to enable debug
